### PR TITLE
#1883 Change link for github logo to PowerPointLabs Repo

### PR DESCRIPTION
**Pull request by ChesterSng**
Changed the link for github logo to [PowerPointLabs](https://github.com/PowerPointLabs/PowerPointLabs) instead of this repo

This PR also shifts the link to the right side of the navbar.

### CODE REVIEW

**Comment by damithc** [comment]
While we are at it, should we right-align the logo?
Also, add `GitHub` in front of the logo? The logo can be a bit smaller, to match the text size.

**Comment by ChesterSng** [comment]
Hi Prof @damithc, just to clarify what you mean by right-align:
Is something like this okay?
image

It looks a bit far away from the other buttons imo

**Comment by damithc** [comment]
Yes, that's what I meant. No need to make it bold though.

**Comment by ChesterSng** [comment]
Made the changes prof @damithc

**Review by blewjy — APPROVED** [review]
LGTM. Link is working. 👍

**Pull request merged**
