### PR TITLE
Automate lossless image compression

### PR DESCRIPTION
**Pull request by alexyaoyang**
### Changes
- Added rake file and image compression gem to automatically compress images after jekyll finishes building.
- Average compression of 30% of all images.
- Rake file can be used for future development, such as minification of CSS.
- Optimized images are on PR #27. 

screenshot 2016-02-28 at 8 15 45 pm
screenshot 2016-02-28 at 8 23 13 pm

This PR is related to PowerPointLabs/PowerPointLabs#952

### CODE REVIEW

**Comment by damithc** [comment]
I thought how much to compress depends on the image resolution and the display size?.  A uniform 30% compression is unlikely to give the optimal result.

**Comment by alexyaoyang** [comment]
@damithc The description was misleading, have changed it, sorry. 

The compression configuration that is used **doesn't** change the image's resolution or dimension, just the image file size. The 30.20% shown in the image is an average compression of all the images that were compressed. The size and resolution of an image doesn't seem to be a significant factor in the compression ratio. Two images of similar sizes and resolution can have very different compression ratio. So a different set of images will probably yield a different compression ratio. 

Effectively, this compression step will [speed up the image loading time for users by ~30%!](http://alexyy.com/2016/02/22/image-compression/)

**Comment by damithc** [comment]
Is it a lossless compression?

**Comment by alexyaoyang** [comment]
@damithc Yes it is lossless compression.

Split view is useful here: https://github.com/PowerPointLabs/PowerPointLabs-Website/pull/27/files?diff=split

**Comment by damithc** [comment]
If lossless, it is ok to automate.

**Comment by alexyaoyang** [comment]
Awesome, thanks!

**Comment by kai33** [comment]
pls refer to https://github.com/PowerPointLabs/PowerPointLabs-Website/blob/master/CONTRIBUTING.md
to reference the issue

**Comment by alexyaoyang** [comment]
Fixed in description for both #27 and #28. Thanks for reminding!

**Comment by kai33** [comment]
It works great, thank you!

**Comment by alexyaoyang** [comment]
Great! Glad it helps! :+1:

**Pull request merged**
