### PR TITLE
Added section on Fill Slide function

### PR DESCRIPTION
**Pull request by junkiattan**
Edits:

1. added in fill slide image
1. updated docs to include a section on fill slide function

### CODE REVIEW

**Comment by leeyh20** [comment]
Should you explain what "fill the slide" means in terms of width/height and whether it will be cropped etc?

**Comment by alexfjw** [comment]
#### Preview
image

**Comment by junkiattan** [comment]
@damithc Requesting your approval for the UI changes.

**Comment by damithc** [comment]
Ok, although an example can be helpful too (but not critical)

**Pull request merged**
