### PR TITLE
Add to reviews

### PR DESCRIPTION
**Pull request by jamos-tay**
Fixes PowerPointLabs/PowerPointLabs#1157

Added this review: http://powerpointlabs.software.informer.com/

### CODE REVIEW

**Review by AngShiYa — APPROVED** [review]
Looks good.

**Review by IanTeo — APPROVED** [review]
LGTM

**Comment by jamos-tay** [comment]
Hi @kai33, can this PR be reviewed? Thanks

**Comment by damithc** [comment]
> Hi @kai33, can this PR be reviewed?

Alternatively, can @yancmo review/merge?

**Review by yancmo — APPROVED** [review]

**Pull request merged**
