### PR TITLE
#145 set favicon for the website

### PR DESCRIPTION
**Pull request by oswellchan**
Added img/logo-small.png which is the favicon image to be used.
Added <link> tag in header to point to img/logo-small.png as favicon

### CODE REVIEW

**Comment by kai33** [comment]
how does it look like in the browser? pls take screenshot of it

**Comment by kai33** [comment]
pls read 
https://github.com/PowerPointLabs/PowerPointLabs-Website/blob/master/CONTRIBUTING.md
to reference an issue properly for this repo

**Comment by oswellchan** [comment]
image

**Comment by oswellchan** [comment]
PowerPointLabs/PowerPointLabs#145

**Pull request merged**
