### PR TITLE
Add nutsandboltsspeedtraining review #1042

### PR DESCRIPTION
**Pull request by IanTeo**
## Changes
* Added nutsandboltsspeedtraning Review (#1042)

This PR is related to [PowerPointLabs/PowerPointLabs#1042](https://github.com/PowerPointLabs/PowerPointLabs/issues/1042)

Fixes PowerPointLabs/PowerPointLabs#1042

### CODE REVIEW

**Comment by damithc** [comment]
@IanTeo some of [these conventions](https://github.com/oss-generic/process/blob/master/docs/QuestionsIssuesPrs.md#submitting-a-pr) are not followed in this PR. E.g. How the `Fixes #...` notation is used. Can you revise?

You can refer PRs in https://github.com/se-edu/addressbook-level4 as examples.

**Comment by IanTeo** [comment]
@damithc as we discussed earlier today, I am unable to use the `Fixes #...` notation.
Regarding the PR name, I do not think that I should use `Add indezine blog post to reviews #1042` as the name as it might be confusing.

Just a suggestion.. Perhaps in the future, such issues for the PowerPointLabs Website should be raised in PowerPointLabs-Website instead of PowerPointLabs.

Lastly, the [contributing](https://github.com/PowerPointLabs/powerpointlabs/blob/master/doc/CONTRIBUTING.md#pull-requests) document in PowerPointLabs says to apply the `status.toReview` label when the PR is ready for review. But we are unable to add labels to the PR. What should I do?

**Comment by damithc** [comment]
> Just a suggestion.. Perhaps in the future, such issues for the PowerPointLabs Website should be raised in PowerPointLabs-Website instead of PowerPointLabs.

Can create a new issue in this repo and post a comment in the other one requesting it to be closed.

> Lastly, the contributing document in PowerPointLabs says to apply the status.toReview label when the PR is ready for review. But we are unable to add labels to the PR. What should I do?

When no able to add labels, just post a comment instead.

**Comment by IanTeo** [comment]
Ok. Understood. Shall I create an issue for this repo for this PR?

**Comment by damithc** [comment]
> Shall I create an issue for this repo for this PR?

Yes, go ahead.

**Comment by IanTeo** [comment]
Hmm.. seems like I cannot raise issues on PowerPointLabs-Website

**Comment by damithc** [comment]
Currently, that repo doesn't even have an issue tracker. Apparently it was a deliberate decision at some point to keep all issues in one repo. Keeping all issues in one repo has some merits, such as easier milestone management. You can revisit this decision towards the end of the semester after using the current set up for a while.

**Comment by damithc** [comment]
For now, you'll have to close the relevant issue manually.
You can use this notation in the meantime `Fixes PowerPointLabs/PowerPointLabs#1042`

**Comment by IanTeo** [comment]
Ready for Review

**Comment by damithc** [comment]
@youthinkk can have a look?
BTW, who is currently in charge of updating the website?

**Comment by kai33** [comment]
looks good to me

**Pull request merged**
