### PR TITLE
#1888 Update Shapes Lab UserGuide

### LINKED ISSUE #1888: Update User Guide for ShapesLab
The UI of ShapesLab have been ported over to WPF. Screenshots will need to be updated.

Edit: It seems the click-drag to select functionality is lost.

### PR DESCRIPTION
**Pull request by YuPeiHenry**
Fixes [#1888](https://github.com/PowerPointLabs/PowerPointLabs/issues/1888)
[Preview](https://deploy-preview-96--powerpointlabs.netlify.com/docs/shapes-lab.html)

### CODE REVIEW

**Review by blewjy — APPROVED** [review]
LGTM

**Comment by YuPeiHenry** [comment]
@damithc The original images had a little variety in shapes. Should I follow that? Currently it uses rectangles only.

**Comment by damithc** [comment]
Yes. Don't use simplistic/trivial examples because if users see that we didn't put effort into examples (it's one of the few things they can pre-judge), they might think we may have similarly slakced on other important aspects. Make examples high-quality and realistic so that we indicate that our work is high quality and we know how to design good presentations.

**Comment by ChesterSng** [comment]
I feel like this screenshot can be improved as well, especially because it is low-res

image

Also, 

image

The screenshots which used the PS2 keyboard example feels a bit discontinued if the reader were to read from top to bottom. Perhaps, we can continue the screenshots from the shape group example given at the start?

**Comment by YuPeiHenry** [comment]
@ChesterSng Images updated based on your suggestions.

**Review by ChesterSng — APPROVED** [review]
LGTM! :)

**Review by damithc — APPROVED** [review]

**Pull request merged**
