### PR TITLE
Update documentation with new features #1171

### LINKED ISSUE #1171: Update documentation with new features
Several PRs merged since the start of the semester have introduced functionality that is not documented on the docs site (powerpointlabs.info):

[User can see a moving magnifier near the tip of the eyedropper #511](https://github.com/PowerPointLabs/PowerPointLabs/pull/1118): Gifs need updating
[Provide a way to prevent revealing future agenda items #695](https://github.com/PowerPointLabs/PowerPointLabs/pull/1092): Document use of empty bullet point
[Highlight Lab: Add 'Remove Highlight' functionality #1107](https://github.com/PowerPointLabs/PowerPointLabs/pull/1121): Document remove highlight functionality
[Provide a way to have hierarchical agendas](https://github.com/PowerPointLabs/PowerPointLabs/pull/1160): Document use of indented bullet points

We should document them so the user is aware that the new functionality exists.

Also feel free to add on if I've missed out any PRs

### PR DESCRIPTION
**Pull request by initialshl**
Partially fixes PowerPointLabs/PowerPointLabs#1171

To reflect the changes of color picker magnifier PowerPointLabs/PowerPointLabs#1118

### CODE REVIEW

**Comment by Skaty** [comment]
As the feature is still in `dev-release`, it would be good if we merge it to a different branch, so that the documentation is not updated with features that aren't available as of yet.

**Review by Skaty — CHANGES_REQUESTED** [review]
The GIF is a little too large, at around 1MB. Try to keep it small, so that it loads fast.

Some methods to reduce filesize:
- Reduce number of colours in GIF file (palette)
- Reduce the dimensions of the image (maybe follow the previous animation's dimensions)

**Comment by damithc** [comment]
> As the feature is still in dev-release, it would be good if we merge it to a different branch, so that the documentation is not updated with features that aren't available as of yet.

Something I've always wondered is if it is better to combine the two repos (website and the app) because the two are supposed to advance together.

**Comment by Skaty** [comment]
It may sound reasonable, but my argument against it would be that the
website cannot be tested separately from the software itself (through CI).

A compromise would be to have in-app offline documentation, rather than to
situate it in the website. That will also allow users to view documentation
without having an internet connection.

**Comment by damithc** [comment]
> It may sound reasonable, but my argument against it would be that the
> website cannot be tested separately from the software itself (through CI).

Um, why not? CI should be able to run any test we specify, right? We can use appveyor for app tests and travis for website tests? 

> A compromise would be to have in-app offline documentation, rather than to
> situate it in the website. That will also allow users to view documentation
> without having an internet connection.

It has benefits. But on the other hand, we cannot update offline documents (e.g. to fix a typo) without doing a new release. We want to minimize public releases because it slows down the PowerPoint startup. Furthermore, the installer will bloat in size due to heavy use of screenshots in our documentation.

**Review by Skaty — APPROVED** [review]

**Comment by kai33** [comment]
Can I merge this pr? is the new feature LIVE?

**Comment by initialshl** [comment]
Not yet, it's still in dev-release

**Pull request merged**
