### PR TITLE
Lossless compression for all images

### PR DESCRIPTION
**Pull request by alexyaoyang**
## Changes
- Losslessly compressed all images used for the website (manually)
- Average compression of 30% each image
- Overall saving for img folder: 29.9 MB to 21.9 MB

Size of image and lossless can be checked easily in Files changed split view.

This PR is related to PowerPointLabs/PowerPointLabs#952.

### CODE REVIEW

**Comment by kai33** [comment]
Is it manually done?
Can it be a part of Jekyll build process and done automatically?

**Comment by kai33** [comment]
there is an additional image img/docs/auto-narrate-5-2.png

**Comment by kai33** [comment]
If the compression cannot be integrated to the build process, developers still need to manually compress any new images, which they usually don't.

So this is like an enhancement for that issue, not a fix.

**Comment by alexyaoyang** [comment]
@kai33 Good point, I will look into that. I think there is a gem that does it. In the meantime, this PR can be labelled as enhancement. I will submit a separate PR for automated image compress at build time. img/docs/auto-narrate-5-2.png has already been compressed.

**Comment by alexyaoyang** [comment]
@kai33 I have created PR #28 for automation of image compression. This PR is still for compressed existing images. Do tell me if you need anything else done for merging, thanks!

**Comment by kai33** [comment]
I'm thinking whether to merge this PR, because
1. it makes the repo size very huge (images in these 2 commits + previous ones in the git history = 100M+)
2. they already can be generated by your automation stuff when build

Does it speed up the compression if these PR's images are used?
Right now it takes me ~15min to compress all

**Comment by alexyaoyang** [comment]
I see your point. Running rake on compressed images just compresses them all again. One way to speed it up is to run rake outside vagrant. 

In any case, I will close this PR for now, until I find a way to skip already compressed images. Sounds good?

**Pull request closed without merging**
