### PR TITLE
Add github logo to navbar

### LINKED ISSUE #1731: Give a link from website to GitHub
In our website, we can show a prominent link to our GitHub project.

Example: 
image

### PR DESCRIPTION
**Pull request by ChesterSng**
Added a white github logo to the navbar that links to [PowerPointLabs Github Page](https://github.com/PowerPointLabs/PowerPointLabs).

image

Will resolve [#1731](https://github.com/PowerPointLabs/PowerPointLabs/issues/1731)

### CODE REVIEW

**Comment by alexfjw** [comment]
How about the official ones?
https://github.com/logos

**Comment by ChesterSng** [comment]
Didn't realise there was a white one inside, changed!
Thanks @alexfjw 

image

**Comment by alexfjw** [comment]
LGTM. @damithc ?

**Comment by damithc** [comment]
> LGTM. @damithc ?

I'm OK with it too.

**Pull request merged**
