### PR TITLE
Add CS3281/82 students as Core Team members

### PR DESCRIPTION
**Pull request by Skaty**
Fixes PowerPointLabs/PowerPointLabs#1164

Screenshot:
image

### CODE REVIEW

**Comment by damithc** [comment]
Can post screenshot?

**Comment by Skaty** [comment]
@damithc

Added screenshot.

**Comment by damithc** [comment]
Looks generally fine. Use PowerPoint to remove gray background from the photos? Several of them has a noticeably darker background.

**Comment by Skaty** [comment]
@damithc Updated the backgrounds.

With background removed:

image

**Comment by damithc** [comment]
Looks good.

**Review by jamos-tay — APPROVED** [review]

**Comment by kai33** [comment]
looks good.
rmb to update new files/pictures permissions to 644 when upload.

**Pull request merged**
