### PR TITLE
Give better example for 'blur all except selected' feature #797

### PR DESCRIPTION
**Pull request by AngShiYa**
Added another example that uses text box with no background color for 'blur all except selected' feature in Effects Lab.

Fixes PowerPointLabs/PowerPointLabs#797

### CODE REVIEW

**Comment by damithc** [comment]
I would like to have an example where the slide looks more effective after applying the effect. We should show both before and after. Even better if the background is not just one image. The power of this feature is that it can blur the entire background whatever it contains, even regular bullet point text. Here's an example, but try to do better.

image

Perhaps you can come up with a few and we can decide which one to use?

**Comment by AngShiYa** [comment]
Okay, I will try to come up with a few. 

Will this example be replacing the existing example? Or are we adding it on top of the existing example?

**Comment by damithc** [comment]
> Will this example be replacing the existing example?

Can replace the existing one.

**Comment by AngShiYa** [comment]
Here's some examples that I came up with.
awesome
For the first example, I'm trying to show that the default powerpoint objects like the slide design, smartart and textboxes can be blurred.

storyboard
For the second example, its more on showing that important parts of a slide can be emphasized. And that it is possible to select multiple objects (picture and textbox) as the exception to blurring.

swot
The last one is to show that slides made up of many shapes and images can also be blurred.

Personally, I feel that the second example is the best. It has the greatest contrast and is focused on the usefulness of the blur effect to emphasize certain portion of the slide.

**Comment by damithc** [comment]
Yes, 2nd one is nice @AngShiYa. Note that we need to distinguish this feature for 'blur remainder' feature. That means blurring behind the selected object should be pronounced. So in that sense the 3rd one is better. Also note that we should not use images that may be copyrighted.

**Comment by AngShiYa** [comment]
Oops. Updated the images. If it is ok, shall I replace the existing example with the third one?

**Comment by damithc** [comment]
It's better now @AngShiYa . It illustrates the technical capabilities of the feature nicely and good enough as an example. Let' try to push beyond 'good enough'. It's not obvious why a presenter want to blur out the four symbols and focus on the word SWOT. The symbols are not distracting or taking attention away from the word. The five things seem to be equally important and are sharing the attention equally. What we need is an example where the background stuff are clearly stealing attention but they are clearly not as important as the foreground object. One more try?

**Comment by AngShiYa** [comment]
@damithc How about this?
charts

**Comment by damithc** [comment]
Looks good @AngShiYa 👍

**Comment by damithc** [comment]
@AngShiYa we want to save copies of sources (e.g. pptx files used to generate screen shots) in case we need to modify them in a future update. If there is an existing pptx file containing sources for effects lab documentation, add this slide to it. If there isn't such a file, start one now.

**Comment by AngShiYa** [comment]
@damithc Seems like there isn't an existing one. I've added a new one.

**Pull request merged**
