### PR TITLE
Update team members

### PR DESCRIPTION
**Pull request by yuhongherald**

### CODE REVIEW

**Comment by damithc** [comment]
Try to make faces roughly the same size.

**Comment by damithc** [comment]
And it's neater if all photos have the same height and the same width.

**Comment by yuhongherald** [comment]
ok

**Comment by yuhongherald** [comment]
@damithc I have adjusted the pictures of the developers to be of the same size, and resized their faces to be similar in size.

**Review by damithc — CHANGES_REQUESTED** [review]
The white gap at the bottom is not ideal. Does it look bad if you move the photo to the bottom? Also, it might help if you enlarge those photos a bit (it's ok for the face to be a bit bigger than others). Example:
image

**Comment by yuhongherald** [comment]
@damithc I have removed the white border at the bottom

**Comment by damithc** [comment]
One more left: `Huang Da`'s photo

**Comment by yuhongherald** [comment]
@damithc I'm so sorry! Also removed the border for Huang Da's photo

**Review by damithc — APPROVED** [review]

**Pull request merged**
