### PR TITLE
Rename Documentation to User Guide #1126

### PR DESCRIPTION
**Pull request by AngShiYa**
Fixes PowerPointLabs/PowerPointLabs#1126

### CODE REVIEW

**Review by Skaty — APPROVED** [review]
LGTM

**Review by jamos-tay — APPROVED** [review]

**Comment by kai33** [comment]
this one also?
https://github.com/PowerPointLabs/PowerPointLabs-Website/blob/master/download.html#L47

**Comment by AngShiYa** [comment]
@kai33 Updated.

**Comment by damithc** [comment]
@AngShiYa Does this affect any incoming links to the previous 'Documentation' page? There are many incoming links to various sections of the documentation page, e.g. in the tutorial pptx file

**Comment by AngShiYa** [comment]
I will check it out

**Comment by AngShiYa** [comment]
@damithc The links are working, but they are linked to the old version (the one before documentation is split into different pages). Some wordings on the pptx are still using "documentation". I will make a PR to update the links and wordings to match the changes.

**Pull request merged**
