### PR TITLE
Changed link to point to the suggested file

### PR DESCRIPTION
**Pull request by vhazali**
Fixes #871

### CODE REVIEW

**Comment by kai33** [comment]
should be full and absolute link path, not this relevant path.
otherwise cannot pass CI

**Comment by vhazali** [comment]
Yup, trying to find the correct link for now

**Comment by kai33** [comment]
pls read 
https://github.com/PowerPointLabs/PowerPointLabs-Website/blob/master/CONTRIBUTING.md
to reference an issue properly for this repo

**Comment by vhazali** [comment]
Fixes PowerPointLabs/PowerPointLabs#871

**Pull request merged**
