### PR TITLE
Added section on Tab Management

### PR DESCRIPTION
**Pull request by junkiattan**
Edits:
1. Added Tab Focus image
1. Included a section on Tab Management  in FAQs

### CODE REVIEW

**Comment by leeyh20** [comment]
Not sure if you want to mention "for PPT 2013 and later, it will switch to the Format tab, thus this will be useful..."

**Comment by alexfjw** [comment]
#### Preview, Content in the Tab Management section is new

image

**Comment by alexfjw** [comment]
Content in the Tab Management section is new

image

**Comment by junkiattan** [comment]
@damithc Requesting your approval for the UI changes

**Comment by damithc** [comment]
This should be documented a regular feature rather than as a FAQ?

**Comment by alexfjw** [comment]
#### Updated Preview 

screen shot 2018-04-15 at 12 42 18 pm

**Comment by junkiattan** [comment]
@damithc I have updated it and moved it over to its own section!

**Comment by damithc** [comment]
Looks fine. I'm wondering if we should name it in a future proof way, such as `General Settings` or something like that so that it can contain more things in future. What do you think?

**Comment by junkiattan** [comment]
@damithc I think that that's a great idea for when we have more settings to be included. From this release until the next one that includes more features, it would be better to keep the current naming to make the function of the checkbox more apparent to users.

When we do include more features, it would then be better to make the naming of the group more general, like "General Settings"

**Comment by damithc** [comment]
hmm... It feels like we are giving a low level feature the treatment of a full Lab.

**Comment by junkiattan** [comment]
@damithc Hm alright. I prefer the current naming, but have no objections against naming it in a more future proof way. Will do it now

Edit: Because dev-release 4.3.0.0 was already released as of the time of writing this note, the naming would be updated to "General Settings" in future releases, especially when more functions are added to "Tab Management".

**Pull request merged**
