### PR TITLE
ShapesLab: New button in pane for adding shape

### PR DESCRIPTION
**Pull request by alexfjw**
Docs for new button in pane for adding shape

### CODE REVIEW

**Comment by alexfjw** [comment]
@leeyh20 @junkiattan, good for a review

**Comment by Skaty** [comment]
Can you provide a screenshot of the updated part?

**Comment by alexfjw** [comment]
We're thinking of doing a full review a bit later. Only text changes in this PR, pictures will come in another PR.

**Comment by alexfjw** [comment]
To add on, we'll be using the following workflow:
everyone commits to some branch since we're doing the docs as a collaborative effort 
When done, we compare against dev release.

(we'll be renaming the current dev release to Pre-release version something, and creating another dev release which will be untouched)

Apologies for the confusion

**Pull request closed without merging**
