### PR TITLE
#1665 Add Save Lab Documentation

### PR DESCRIPTION
**Pull request by junkiattan**
Updates the documentation for Save Lab. Steps have been taken to ensure that the features are accurately described and that the text follows the style of existing website documentation.

The text content has been reviewed by @damithc, hence it should be good to go

### CODE REVIEW

**Comment by junkiattan** [comment]
@initialshl @leeyh20 @alexfjw Would appreciate the quick review and approval. Prof Damith has already given the go ahead for the text content.

Alex/YanHwa, would need your help with the pictures for Save Lab. Can further discuss on this

**Comment by alexfjw** [comment]
### Preview of Changes
image

**Comment by damithc** [comment]
Looks fine.

> **_Load_** icon to ...

Ensure that you use the same kind of formatting we use when we refer to an icon elsewhere in the user guide.

**Comment by junkiattan** [comment]
@damithc Don't worry prof, that part has been removed to ensure consistency with the rest of the instructions. Curreent instructions should be clear enough for users to navigate through

**Review by alexfjw — APPROVED** [review]

**Pull request merged**
