### PR TITLE
#1837 Tooltips Lab: User Guide

### LINKED ISSUE #1837: Update documentation for TooltipsLab
We need to update the following for TooltipsLab: 
- [x] Tutorial.pptx
- [ ] User Guide on PowerPointLabs Website

### PR DESCRIPTION
**Pull request by blewjy**
Fixes PowerPointLabs/PowerPointLabs#1837.

Done by @YuPeiHenry, @ChesterSng and myself.

### CODE REVIEW

**Comment by damithc** [comment]
Preview: https://deploy-preview-93--powerpointlabs.netlify.com/docs/tooltips-lab.html

There seems to be some image size issues.

**Comment by blewjy** [comment]
Fixed! Should be working now

**Comment by ChesterSng** [comment]
LGTM!

**Comment by YuPeiHenry** [comment]
LGTM

**Comment by ChesterSng** [comment]
Prof @damithc, can we merge this?

**Comment by damithc** [comment]
> Prof @damithc, can we merge this?

Go ahead 👍

**Pull request merged**
