### PR TITLE
Break up the documentation page into multiple pages #1049

### PR DESCRIPTION
**Pull request by BCDarkKnight**
Fixes PowerPointLabs/PowerPointLabs#1049
- Split docs to multiple pages
- Add subsections to right navigation bar
- Add next previous page buttons at bottom of page

### CODE REVIEW

**Comment by youthinkk** [comment]
The long page is finally broken down into parts!! Good Job 👍 
However, you might take following inputs into the considerations. Let me know if I am mistaken anything.

# Font Consistency for Links

The font size (or bold?) for "Installation Guide" and "Quick Start Tutorial" are not consistent. 
link_consistency
</br>

# Alignment of "Frequently Asked Questions"

Although the gray "Frequently Asked Question" at the bottom is at the center of the page, it looks a bit strange. Will it be better if the button can be right aligned with the document text?
frequently_questions
</br>

# Scrolling of Menu and Page
- When scrolling the menu, the page also moves at the same time. The user might get confused which one he/she is scrolling (I am one of them). The page should be static while menu is scrolled.
- I like the highlight of menu that shows which section I am in. However, the highlight will not be shown if the listed menu is not within the page range. 
  missing_highlight

**Comment by BCDarkKnight** [comment]
Alignment:
image
Wouldn't it look weird here? Or should just remove the next and prev buttons?

Scrolling:
Which browser are you using? The page does not scroll together with the menu when I test it in Chrome and Firefox. If the menu is at the top/bottom and the user scrolls further top/bottom using mouse wheel or keyboard, then the page will scroll. Do you want to prevent the page from scrolling when the menu is at the top/bottom?

**Comment by youthinkk** [comment]
The scrolling works perfectly fine now! It looks great to me! 

For the previous and next buttons, I feel it looks better with the new alignment. However, you might want to check with @damithc which is better.

**Comment by damithc** [comment]
@fionachang Perhaps you can upload it to our dev website for others to have a look? http://www.comp.nus.edu.sg/~pptlabs/dev/

**Comment by kai33** [comment]
it's pretty cool, and now the page can be loaded much faster.
the codes look good

**Comment by damithc** [comment]
Yup. Good work @fionachang :+1: 
Can release when you are ready.

**Comment by Dawnlord** [comment]
May I merge it now? Then I can update the PR `rename the features`.

**Pull request merged**
